version: '3'

name: FAERS

services:
  app:
    build: ./app/container
    container_name: app
    volumes:
      - ./app:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini
    restart: always
  web:
    image: nginx:latest
    container_name: web
    ports:
      - 8000:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    restart: always

volumes:
  socket:
