version: '3'

name: FAERS

services:
  app:
    build: ./app/main/container
    container_name: app
    volumes:
      - ./data:/data
      - ./app/main:/app/main
      - ./app/common:/app/common
      - socket:/tmp
    command: uwsgi --ini /app/main/app.ini
    restart: always
  web:
    image: nginx:latest
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    restart: always

volumes:
  socket:
